accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  path('', views.IndexView, name='index'),
  path('<int:page>', views.IndexView, name='index'),
  path('posts/<int:pk>', views.createpost, name='posts'),
  path('posts/<int:pk>/<int:page>', views.createpost, name='posts'),
  path('mypage/', views.mypage, name='mypage'),
  path('good/', views.good, name='good'),
  path('delete/<int:delete_id>', views.delete, name='delete'),
  path('users/', views.users, name='users'),
  path('explain/', views.explain.as_view(), name='explain'),
]

venaqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('accounts.urls')),
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
        template_name = 'password_reset.html'),
        name = 'password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
        template_name = 'password_reset_sent.html'),
        name = 'password_reset_done'),
    path('reset/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(
        template_name = 'password_reset_form.html'),
        name = 'password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
        template_name = 'password_reset_done.html'),
        name = 'password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

post/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.

class Post(models.Model):
    owner = models.ForeignKey(
        CustomUser, 
        on_delete=models.CASCADE,
        related_name='owner_id',)
    to_user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,)
    content = models.TextField(
        max_length=1000,
        name='content')
    good_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + ' (' + str(self.to_user.username) + ')'

class Good(models.Model):
    owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='good_owner')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return 'good for "' + str(self.post) + '" (by ' + str(self.owner) + ')'

post/forms.py
from django.forms import ModelForm
from .models import Post, Good
from django import forms

# class PostForm(ModelForm):
#     '''
#     '''
#     class Meta:
#         '''
#         Attributes:
#           model:
#           fields:
#         '''
#         model = Post
#         fields = ['content']

class GoodForm(ModelForm):
    class Meta:
        model = Good
        fields = ['owner', 'post']

class CreatePostForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())

# class CreatePostForm(forms.Form):
#     content = forms.CharField(widget=forms.Textarea(attrs={'cols': '60', 'rows': '10'}))

post/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreatePostForm
from django.contrib.auth.decorators import login_required
from .models import Post, Good
from accounts.models import CustomUser
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Sum
# import json
from django.http import JsonResponse

# Create your views here.

@login_required
def IndexView(request, page=1):
    # userのデータを取得
    my_data = CustomUser.objects.get(id=request.user.id)
    # userへの投稿の総合数を取得
    my_posts = Post.objects.filter(to_user=request.user.pk).count()
    # それな！も総合数を取得
    my_goods = Post.objects.filter(to_user=request.user.pk).aggregate(Sum('good_count'))['good_count__sum']
    if (my_goods == None):
        my_goods = 0
    print(my_goods)
    

    # userに送られたpostを取得
    posts = Post.objects.filter(to_user=request.user.id).order_by('good_count').reverse()
    data = Paginator(posts, 8)
    params = {
        'login_user':request.user,
        'my_data':my_data,
        'posts': data.get_page(page),
        'my_posts':my_posts,
        'my_goods':my_goods,
    }

    return render(request, 'index.html', params)

@login_required
def createpost(request, pk, page=1):
    # <int:id>の取得をする
    to_user = CustomUser.objects.get(pk=pk)
    # userへの投稿の総合数を取得
    to_posts = Post.objects.filter(to_user=to_user).count()
    # それな！も総合数を取得
    to_goods = Post.objects.filter(to_user=to_user).aggregate(Sum('good_count'))['good_count__sum']

    # 印象を匿名で送信する
    if request.method == 'POST':
        # c = request.POST['content']
        c = request.POST.get('content')
        # postを作成する
        p = Post()
        p.owner_id = request.user.pk
        # page/<int:id>を引っ張ってきてto_userにする
        p.to_user = to_user
        p.content = c
        p.save()
        print(c)
        d = {
            'content': p.content,
        }
        return JsonResponse(d, json_dumps_params={'ensure_ascii': False})
        # return redirect(to='post:posts', pk=to_user.id)

    # UserへのPostを取得
    posts = Post.objects.filter(to_user=pk).order_by('good_count').reverse()
    data = Paginator(posts, 8)

    # 共通処理
    params = {
            'login_user':request.user,
            'form':CreatePostForm,
            'to_user':to_user,
            'posts':data.get_page(page),
            'to_posts':to_posts,
            'to_goods':to_goods,
        }

    return render(request, 'post.html', params)

@login_required
def mypage(request):

    # 共通処理
    params = {
        'login_user':request.user,
    }

    return render(request, 'mypage.html', params)

@login_required
def good(request):
    if request.method == 'GET':
        good = request.GET.get('good_id')
        print(good)
        # goodするpostを取得
        good_post = Post.objects.get(id=good)
        # 自分がpostにgoodした数を調べる
        is_good = Good.objects.filter(owner=request.user).filter(post=good_post).count()
        # ゼロより大きければすでにgood済み
        if is_good > 0:
            error_data = {
                'good_id':good_post.id,
                'error':'既にそれな！しています。',
            }
            return JsonResponse(error_data)
        
        # Postのgood_countを1増やす
        good_post.good_count += 1
        good_post.save()
        # Goodを作成し、設定して保存
        good = Good()
        good.owner = request.user
        good.post = good_post
        good.save()
        d = {
            'good_id':good_post.id,
            'good_count':good_post.good_count,
            'success':'それな！しました。'
        }
        return JsonResponse(d)

@login_required
def delete(request, delete_id):
    # deleteするpostを取得
    delete_id = Post.objects.get(id=delete_id)
    # postを削除
    delete_id.delete()
    messages.success(request, '削除しました！')
    return redirect('post:index')

@login_required
def users(request):
    # 総登録者数を取得
    users = CustomUser.objects.all().count()

    if request.method == 'GET':
        if request.GET.get('count'):
            count = request.GET.get('count')
            now_users = CustomUser.objects.all().count()
            print(count)
            d = {
                'count': now_users,
            }
            print(count)
            print(now_users)
            print(now_users - int(count))
            return JsonResponse(d)

    #共通処理
    params = {
        'login_user': request.user,
        'users': users,
    }

    return render(request, 'users.html', params)

class explain(TemplateView):
    '''
    '''
    template_name = 'explain.html'

post/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="decription" content="">
    <title>{% block title %}ベナキー{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'post/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/users.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/explain.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti&family=Noto+Sans+JP:wght@400;700&family=Noto+Serif+JP:wght@200;400;600;900&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  </head>

  <header id="header">
    <h1 class="headerImg">VENAQUI</h1>
    <div class="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <nav class="globalMenuSp">
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'post:index' %}">マイページ</a></li>
        <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
        <li><a href="{% url 'password_reset' %}">パスワードのリセット</a></li>
        <li><a href="{% url 'post:users' %}">総会員数</a></li>
        <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
        {% else %}
        <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
        <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
        <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>

  <div class="humburger_backimage hidden"></div>
  
  <body>
      {% block contents %}{% endblock %}
      {% block extrajs %}
<script>
  /** jQueryの処理 */
  var h = 'Hello World'
  console.log(h)
  
  var num = $('#users_count').text()
  var result = Number(num)
  
  function count() {
    setTimeout(count, 1000);
      $.ajax({
        url: "{% url 'post:users' %}",
        method: "GET",
        data: {'count': $('#users_count').text()},
        success:function(response) {
          const c = response.count;
          $('#users_count').text(c)
        }
      })
  };

  // ↓これで実行する
  // count();

      function copyToClipboard() {
        // コピー対象をJavaScript上で変数として定義する
        var copyTarget = document.getElementById("copyTarget");

        // コピー対象のテキストを選択する
        copyTarget.select();

        // 選択しているテキストをクリップボードにコピーする
        document.execCommand("Copy");

        // コピーをお知らせする
        alert("コピーできました！ : " + copyTarget.value);
    }

    $(function() {
  var header = $('#header');
  var headerImg = $('.headerImg');
  $('.hamburger').click(function() {
      $(this).toggleClass('active');
      if ($(this).hasClass('active')) {
          $('.globalMenuSp').addClass('active');
          $('.humburger_backimage').removeClass('hidden');
      } else {
          $('.globalMenuSp').removeClass('active');
          $('.humburger_backimage').addClass('hidden');
      }
  });
  });
</script>
{% endblock %}
  </body>

  <footer>
    <p>&copy; 2021 All rights reserved by RAMBIIS.</p>
  </footer>
</html>

post/templates/explain.html
{% extends 'base.html' %}
{% block title %}VENAQUIとは{% endblock %}

{% block contents %}
<main>
  <div class="explain_back">
    <h2>VENAQUI（ベナキー）って何？</h2>
    <p>VENAQUIとは、SNSにマイページのリンクを貼り、友達から匿名で自分の印象を投稿してもらい、その投稿に「それな！」で色々な人に共感してもらう事で自分の客観的意見を知ることができるサービスです！</p>
      <div class="explain_first">
        <div class="explain_first_images">
          <img src="../../media/images/explain_instagram.png" />
          <img src="../../media/images/explain_twitter.png" />
        </div>
        <h3>SNSにリンクを貼って自分の印象を匿名で教えて貰おう！</h3>
      </div>
      <div class="explain_second">
        <img src="../../media/images/explain_second.png" />
        <h3>教えてもらった印象に共感した人に「それな！」して貰おう！</h3>
      </div>
      <div class="explain_last">
        <p>※あくまで他人の意見です。強く聞き入れすぎずに、参考する程度にVENAQUIをお楽しみ下さい。</p>
      </div>
      {% if not user.is_authenticated %}
      <div class="to_login">
        <a href="{% url 'accounts:signup' %}">アカウント新規登録はこちらから</a>
      </div>
      {% endif %}
  </div>
</main>
{% endblock %}

post/templates/index.html
{% extends 'base.html' %}
{% block title %}ベナキー{% endblock %}

  {% block contents %}
  <main>

  {% if user.is_authenticated %}
  
  {% include 'mypage.html' %}

  {% endif %}
  </main>
{% endblock %}

post/templates/mypage.html
  <div class="mypage">
    <div class="profile">
      <div class="top">
        <div class="image">
          <img src="{{ my_data.image.url }}">
        </div>
        <div class="text">
          <p id="username">{{my_data.username}}</p>
          <div class="count">
            <div class="post">
              <p class="post_title">ポスト</p>
              <p >{{ my_posts }}</p>
            </div>
            <div class="good">
              <p class="good_title">それな！</p>
              <p>{{ my_goods }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- コピー対象要素とコピーボタン -->
      <div class="link">
        <p>SNSにリンクを貼って匿名で印象を聞こう！</p>
        <input id="copyTarget" type="text" value="https://venaqui.herokuapp.com/{{my_data.id}}" readonly>
        <button onclick="copyToClipboard()">Copy text</button>
      </div>
    </div>

    <!-- Messages表示 -->
    {% if messages %}
      {% for message in messages %}
      <p>{{message}}</p>
      {% endfor %}
      {% endif %}
      
    <!-- Post一覧 -->
    <div class="posts">
      {% for post in posts %}
      <div class="post">
        <p id="t">{{post.content}}</p>
        <div class="under">
          <a href="{% url 'post:delete' post.id %}">削除する</a>
          <p><span id="good_count">{{post.good_count}}</span>それな！</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="paginator">
    <ul>
      {% if posts.has_previous %}
      <li><a class="hover" href="{% url 'post:index' %}"><<</a></li>
      <li><a class="hover" href="{% url 'post:index' %}{{posts.previous_page_number}}">前のページ</a></li>
      {% else %}
      <li><a class="none"><<</a></li>
      <li><a class="none">前のページ</a></li>
      {% endif %}
      <li><a>{{posts.number}}/{{posts.paginator.num_pages}}</a></li>
      {% if posts.has_next %}
      <li><a class="hover" href="{% url 'post:index' %}{{posts.next_page_number}}">次のページ</a></li>
      <li><a class="hover" href="{% url 'post:index' %}{{posts.paginator.num_pages}}">>></a></li>
      {% else %}
      <li><a class="none">次のページ</a></li>
      <li><a class="none">>></a></li>
      {% endif %}
    </ul>
  </div>

post/templates/post.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="decription" content="">
    <title>{% block title %}ベナキー{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'post/css/posts.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  </head>

  <header id="header">
    <h1 class="headerImg">VENAQUI</h1>
    <div class="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <nav class="globalMenuSp">
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'post:index' %}">マイページ</a></li>
        <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
        <li><a href="{% url 'password_reset' %}">パスワードのリセット</a></li>
        <li><a href="{% url 'post:users' %}">総会員数</a></li>
        {% else %}
        <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
        <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>

  <div class="humburger_backimage hidden"></div>
  
  <body>
{% block contents %}
<main>
<div class="to_page">
  <div class="profile">
    <div class="top">
      <div class="image">
        <img src="{{ to_user.image.url }}">
      </div>
      <div class="text">
        <p id="username">{{ to_user.username }}</p>
        <div class="count">
          <div class="post">
            <p class="post_title">ポスト</p>
            <p >{{ to_posts }}</p>
          </div>
          <div class="good">
            <p class="good_title">それな！</p>
            <p>{{ to_goods }}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="make">
        <button class="before_postform_button">匿名で印象を伝える</button>
        <div class="content_form_div hidden"></div>
        <div class="content_form_back hidden">
          <form id="content_form" action="{% url 'post:posts' to_user.id %}" method="post">
            {% csrf_token %}
            {{ form.content }}<br>
            <button id="content_form_button" type="submit">伝える</button>
          </form>
        </div>
    </div>
  </div>

  <div class="to_posts">
  <!-- UserのPost一覧 -->
  {% for post in posts %}
    <div class="post">
      <p id="t">{{post.content}}</p>
      <div class="under">
        <span class="message_{{post.id}}"></span>
        <span class="count_{{post.id}}">{{post.good_count}}</span>
        <a class="good" name="{{post.id}}" type="button">それな！</a>
      </div>
    </div>
  {% endfor %}
  </div>
</div>

  <div class="paginator">
    <ul>
      {% if posts.has_previous %}
      <li><a class="hover" href="{% url 'post:posts' to_user.id %}"><<</a></li>
      <li><a class="hover" href="{% url 'post:posts' to_user.id %}/{{posts.previous_page_number}}">前のページ</a></li>
      {% else %}
      <li><a class="none"><<</a></li>
      <li><a class="none">前のページ</a></li>
      {% endif %}
      <li><a>{{posts.number}}/{{posts.paginator.num_pages}}</a></li>
      {% if posts.has_next %}
      <li><a class="hover" href="{% url 'post:posts' to_user.id %}/{{posts.next_page_number}}">次のページ</a></li>
      <li><a class="hover" href="{% url 'post:posts' to_user.id %}/{{posts.paginator.num_pages}}">>></a></li>
      {% else %}
      <li><a class="none">次のページ</a></li>
      <li><a class="none">>></a></li>
      {% endif %}
    </ul>
  </div>
</main>

  {% block extrajs %}
  <script charset="utf-8">
    var i = 'Hello World';
    console.log(i)

    var token = '{{csrf_token}}';

    $('#content_form').on('submit', function(e) {
      e.preventDefault();
      var form = $(this);
      $.ajax({
          url: "{% url 'post:posts' to_user.id %}",
          method: 'POST',
          dataType: 'json',
          headers: { "X-CSRFToken": token },
          data: {
              content: $('#id_content').val(),
          },
          success:function(response){
            const c = response.content;
            alert(c)
            $('#id_content').val('');
            location.reload();
          },
      })
      console.log(content)
    })

  $('.good').on('click', function(){
    var post_id = $(this).attr('name')
    console.log(post_id)
    $.ajax({
        url: "{% url 'post:good' %}",
        method: "GET",
        dataType: 'json',
        data: {
            good_id: post_id,
        },
        success: function(response){
            const response_id = response.good_id;
            const good_count = response.good_count;
            $('.count_' + response_id).text(good_count);
            const success = response.success;
            const error = response.error;
            if (response.error) {
              console.log(error)
              $('.message_' + response_id).text('既にそれな！しています。');
            } else {
              console.log(success)
              $('.message_' + response_id).text('それな！しました。');
            }
            console.log(response)
        }
    })
  })

$(function() {
  var header = $('#header');
  var headerImg = $('.headerImg');
  $('.hamburger').click(function() {
      $(this).toggleClass('active');
      if ($(this).hasClass('active')) {
          $('.globalMenuSp').addClass('active');
          $('.humburger_backimage').removeClass('hidden');
      } else {
          $('.globalMenuSp').removeClass('active');
          $('.humburger_backimage').addClass('hidden');
      }
  });
  });

  $('.before_postform_button').on('click', function(){
    var form_div = $('.content_form_div');
    var form_back = $('.content_form_back');
    form_div.removeClass('hidden');
    form_back.removeClass('hidden');
  });

  $('.content_form_div').on('click', function(){
    var form_div = $('.content_form_div');
    var form_back = $('.content_form_back');
    form_div.addClass('hidden');
    form_back.addClass('hidden');
  });
  </script>
  {% endblock %}

{% endblock %}
</body>

<footer>
  <p>&copy; 2021 All rights reserved by RAMBIIS.</p>
</footer>
</html>

post/templates/users.html
{% extends 'base.html' %}
{% block title %}総登録者{% endblock %}

{% block contents %}
<main>
  <div class="users_text">
    <img src="../../media/images/users_background_image.jpg" />
    <div class="users_center">
      <h1 id="users_title"> VENAQUIユーザー総数</h1>
      <p id="users_count">{{users}}</p>
    </div>
  </div>
</main>
{% endblock %}