accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  path('', views.IndexView, name='index'),
  path('<int:page>', views.IndexView, name='index'),
  path('posts/<int:pk>', views.createpost, name='posts'),
  path('posts/<int:pk>/<int:page>', views.createpost, name='posts'),
  path('mypage/', views.mypage, name='mypage'),
  path('good/', views.good, name='good'),
  path('delete/<int:delete_id>', views.delete, name='delete'),
  path('users/', views.users, name='users'),
  path('explain/', views.explain.as_view(), name='explain'),
]

venaqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('accounts.urls')),
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
        template_name = 'password_reset.html'),
        name = 'password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
        template_name = 'password_reset_sent.html'),
        name = 'password_reset_done'),
    path('reset/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(
        template_name = 'password_reset_form.html'),
        name = 'password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
        template_name = 'password_reset_done.html'),
        name = 'password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _
from datetime import date
import uuid

# Create your models here.

# class UserManager(UserManager):
#     def _create_user(self, email, password, **extra_fields):
#         email = self.normalize_email(email)
#         user = self.model(email=email, **extra_fields)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user

#     def create_user(self, email, password=None, **extra_fields):
#         extra_fields.setdefault('is_staff', False)
#         extra_fields.setdefault('is_superuser', False)
#         return self._create_user(email, password, **extra_fields)

#     def create_superuser(self, email, password, **extra_fields):
#         extra_fields.setdefault('is_staff', True)
#         extra_fields.setdefault('is_superuser', True)

#         if extra_fields.get('is_staff') is not True:
#             raise ValueError('Superuser must have is_staff=True.')
#         if extra_fields.get('is_superuser') is not True:
#             raise ValueError('Superuser must have is_superuser=True.')

#         return self._create_user(email, password, **extra_fields)

# class CustomUser(AbstractUser):
#     username = models.CharField(_('username'), max_length=150, blank=True)
#     email = models.EmailField(_('email address'), unique=True)

#     objects = UserManager()

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = []

def image_directory_path(instance, filename):
    return 'photos/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

class CustomUser(AbstractUser):
    email = models.EmailField('email', unique=True)
    image = models.ImageField('image', upload_to=image_directory_path)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms

class CustomUserCreationForm(UserCreationForm):
    '''
    '''
    class Meta:
        '''

        Attributes:
          model:
          fields:
        '''
        model = CustomUser
        fields = ('image', 'username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm

# Create your views here.

class SignUpView(CreateView):
    '''
    '''
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        '''
        parameters:
          from(django.forms.Form)
        Return:
        '''
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    '''
    '''
    template_name = "signup_success.html"

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>ログイン</title>
  <!-- Custom styles for this template -->
  <link href="{% static 'accounts/css/login.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'post/css/header.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</head>

<header id="header">
  <h1 class="headerImg">VENAQUI</h1>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="globalMenuSp">
    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'post:index' %}">マイページ</a></li>
      <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
      <li><a href="{% url 'password_reset' %}">パスワードのリセット</a></li>
      <li><a href="{% url 'post:users' %}">総会員数</a></li>
      <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
      {% else %}
      <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
      <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
      <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
      {% endif %}
    </ul>
  </nav>
</header>

<div class="humburger_backimage hidden"></div>

<body class="text-center">
  <main>
    <div class="form-login">
    {% if form.errors %}
    <p style="color: red">ユーザー名とパスワードが一致しません</p>
    {% endif%}

    <h2 id="venaqui">VENAQUI</h2>
    <h3>匿名で友達から君の印象を聞こう！</h3>
    <!--ログインフォームを配置-->
    <div class="form">
      <form class="signup" method="post">
        {% csrf_token %}
        <div class="mail">
          <label id="username" for="Username" class="visually-hidden">メールアドレス</label><br>
          <input type="text" name="username" id="id_username" max_length="200" autocapitalize="none" autocomplete="username"
            class="form-control" placeholder="example@gmail.com" required autofocus>
        </div>
        <div class="password">
          <label id="pin" for="Password" class="visually-hidden">パスワード</label><br>
          <input type="password" name="password" id="id_password" autocomplete="current-password" class="form-control"
            placeholder="password" required>
        </div>
          <p class="forget"><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p>
          <input id="login" class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">
      </form>
      <p id="to_signup">アカウントをお持ちではないですか？<a href="{% url 'accounts:signup' %}">登録する</a></p>
    </div>
  </div>
  </main>

<script>
    $(function() {
  var header = $('#header');
  var headerImg = $('.headerImg');
  $('.hamburger').click(function() {
      $(this).toggleClass('active');
      if ($(this).hasClass('active')) {
          $('.globalMenuSp').addClass('active');
          $('.humburger_backimage').removeClass('hidden');
      } else {
          $('.globalMenuSp').removeClass('active');
          $('.humburger_backimage').addClass('hidden');
      }
  });
  });
</script>
</body>

</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}ログアウト{% endblock %}

    {% block contents %}
    <div class="container">
      <h3>ログアウトしました</h3>
      <p><a href="{% url 'post:index' %}">トップページへ</a></p>
    </div>
    {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Reset password{% endblock %}

    {% block contents %}
    <div class="container">
          <hr>
          <h3>パスワードをリセットしますか？</h3>
          <p>
            登録済みのメールアドレスを入力してください。
            パスワードリセットのリンクを記載したメールをすぐにお届けします。
          </p>
          <br>
          <form action="" method="post" class="text-ceneter">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="メールを受け取る"><br>
          </form>
          <a href="{% url 'post:index' %}">トップページへ</a>
    </div>
    {% endblock %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>
  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <a href="{% url 'post:index' %}">トップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>
  <body>
    <div class="pad">
      <h2>VENAQUI</h2>
      <h4>
        新しいパスワードを2回入力してください。これにより、
        正しく入力できたことが確認されます。
      </h4>
      <br />
      <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="パスワードリセット"/>
      </form>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}Send password reset{% endblock %}

    {% block contents %}
    <div class="container">
          <hr>
          <h5>パスワードのリセット手順をメールで送信しました。
            メールはすぐに届きます。</h5>
          <br>
          <h6>
            メールが届かない場合は、登録済みのメールアドレスであるかを確認し、迷惑メールフォルダーも確認してみてください。
          </h6>
          <br>
          <a href="{% url 'post:index' %}">トップページへ</a>
    </div>
    {% endblock %}

accounts/templates/signup.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>会員登録</title>
  <!-- Custom styles for this template -->
  <link href="{% static 'accounts/css/signup.css' %}" rel="stylesheet">
  <link href="{% static 'post/css/header.css' %}" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</head>

<header id="header">
  <h1 class="headerImg">VENAQUI</h1>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="globalMenuSp">
    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'post:index' %}">マイページ</a></li>
      <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
      <li><a href="{% url 'password_reset' %}">パスワードのリセット</a></li>
      <li><a href="{% url 'post:users' %}">総会員数</a></li>
      <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
      {% else %}
      <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
      <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
      <li><a href="{% url 'post:explain' %}">VENAQUIとは</a></li>
      {% endif %}
    </ul>
  </nav>
</header>

<div class="humburger_backimage hidden"></div>

<body>
  <main>
    <div class="signup">
      <h2>VENAQUI</h2>
      <h3>登録して友達に匿名で印象を聞こう</h3>
      <div class="form">
        <form method="post" novalidate enctype="multipart/form-data">
          {% csrf_token %}
          <p>
            <span class="tag">プロフィール画像:</span>
            <br>{{ form.image }}<br>
            {% for error in form.image.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </p><br>
          <p>
            <span class="tag">ユーザー名:</span><br>
            {{ form.username }}<br>
            {% for error in form.username.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </p><br>
          <p>
            <span class="tag">メールアドレス:</span><br>
            {{ form.email }}<br>
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </p><br>
          <p>
            <span class="tag">パスワード:</span><br>
            {{ form.password1 }}<br>
            {% for error in form.password1.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </p><br>
            <p>
            <span class="tag">パスワード(確認用):</span><br>
            {{ form.password2 }}<br>
            {% for error in form.password2.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </p><br>
        <input id="make" type="submit" value="登録する">
        </form>
      </div>
      <p class="to_login"><a href="{% url 'accounts:login' %}">
        ログインはこちら
      </a></p>
      <p class="to_top"><a href="{% url 'post:index' %}">
        トップページに戻る
      </a></p>
    </div>
  </main>

  <script>
    $(function() {
  var header = $('#header');
  var headerImg = $('.headerImg');
  $('.hamburger').click(function() {
      $(this).toggleClass('active');
      if ($(this).hasClass('active')) {
          $('.globalMenuSp').addClass('active');
          $('.humburger_backimage').removeClass('hidden');
      } else {
          $('.globalMenuSp').removeClass('active');
          $('.humburger_backimage').addClass('hidden');
      }
  });
  });
</script>
  </body>
  </html>

accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}登録完了{% endblock %}

    {% block contents %}
    <div class="success">
      <h3>登録が完了しました</h3>
      <p>君の印象を教えてもらおう！</p>
      <p><a href="{% url 'accounts:login' %}">
        ログインはこちら
      </a></p>
    </div>
    {% endblock %}